name: CI Checks

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '22.15.1' # set this to the node version to use (e.g. '8.x', '10.x', '12.x')

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install project
        run: |
          npm install

      - name: Check for lint errors
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm run test
